# Report (log to stdout) host statistics
#

FROM google/cadvisor:v0.23.2
MAINTAINER  bellis

# Install build deps
#
RUN apt-get update && apt-get -y -q install \
	python \
    python-dev \
    python-distribute \
    python-pip \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install pyCLI==2.0.3 psutil==4.2.0 requests==2.10.0 python-json-logger==0.1.5

# Copy logger script
#
COPY host-stats-logger.py /host-stats-logger.py

ENTRYPOINT ["python", "-u", "/host-stats-logger.py"]
CMD ["-cmdn"]
